#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Generate esphome/ui-images.yaml from assets/device_assets.json.

The generated package declares one ESPHome image per device asset (loaded from
${kis_segito_assets}, a local folder or a raw GitHub URL) and hands them to the
kis_segito_ui component by key (<icon>_<size>).

Usage: gen_esphome_images.py
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
MANIFEST = ROOT / "assets" / "device_assets.json"
OUT = ROOT / "esphome" / "ui-images.yaml"


def main() -> int:
    manifest = json.loads(MANIFEST.read_text("utf-8"))
    keys = [
        f"{icon}_{size}"
        for icon, sizes in manifest.items()
        if not icon.startswith("_")
        for size in sizes
    ]
    lines = [
        "# SPDX-License-Identifier: AGPL-3.0-only",
        "#",
        "# Generated by tools/gen_esphome_images.py from assets/device_assets.json.",
        "",
        "image:",
        "  - platform: file",
        "    defaults:",
        "      type: RGB565",
        "      transparency: alpha_channel",
        "    files:",
    ]
    for key in keys:
        lines += [f"      - id: ks_img_{key}", f"        file: ${{kis_segito_assets}}/{key}.png"]
    lines += [
        "",
        "kis_segito_ui:",
        "  id: ui",
        "  number_font: font_number",
        "  action_sensor: knob_action",
        "  images:",
    ]
    lines += [f"    {key}: ks_img_{key}" for key in keys]
    OUT.write_text("\n".join(lines) + "\n", "utf-8")
    print(f"wrote {len(keys)} images to {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
